### ISSUE TITLE
Feature: customizable croppers

### ISSUE THREAD

**Issue by RahmeVictor** [kekland/croppy#4]
I use this library to crop documents which are always white and it is very hard to see the cropper.

**Comment by kekland** [comment]
Hi! Thanks for your feedback!

I'm currently on a bit of a break, but there are plans to create a very easy way to make your own fully custom cropper. In the meantime it's technically - possible to make one, but that would involve copy-pasting a lot of code from the repository and adjusting the color property on the crop handles.

If this is something that you need urgently, I can send a detailed explanation on how you can build your own custom cropper (until support for an easier way will come, but that's 1-2 months away from now).

**Comment by RahmeVictor** [comment]
Thanks for the quick response, it's not that urgent. This library is awsome, can't wait to see it finished.

**Comment by kekland** [comment]
Hey folks! Support for creating custom croppers alongside with extensive documentation has been added in version 0.2.3. Feel free to check out the updated documentation in https://github.com/kekland/croppy/blob/0.2.3/doc/doc.md, which should cover everything from the data layer, geometry, to presentation. At the end there's a section on how you can compose croppy's widgets to create your own cropper. 

Note that the custom croppers is still a bit experimental and the way how they're created may feel a bit too boilerplate-y, but this is done so that any kind of a cropper can be created. If you have any ideas or suggestions as to how this flow can be improved, please let me know!

cc @RahmeVictor @umbertogrimaldi

**Comment by RahmeVictor** [comment]
I have used the new crop builders and they work perfectly. Thanks!
